-- MySQL Script generated by MySQL Workbench
-- Qui 06 Set 2018 19:16:10 -03
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema reformando_banco
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema reformando_banco
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `reformando_banco` DEFAULT CHARACTER SET utf8 ;
USE `reformando_banco` ;

-- -----------------------------------------------------
-- Table `reformando_banco`.`pessoas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `reformando_banco`.`pessoas` (
  `idpessoas` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `apelido` VARCHAR(45) NULL,
  `cpf` VARCHAR(12) NOT NULL,
  `endereco` VARCHAR(45) NOT NULL,
  `bairro` VARCHAR(45) NOT NULL,
  `cidade` VARCHAR(45) NOT NULL,
  `telefone` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idpessoas`),
  UNIQUE INDEX `cpf_UNIQUE` (`cpf` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `reformando_banco`.`profissionais`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `reformando_banco`.`profissionais` (
  `idprofissionais` INT NOT NULL AUTO_INCREMENT,
  `pessoas_idpessoas` INT NOT NULL,
  `profissao` VARCHAR(45) NOT NULL,
  `qualificacao` VARCHAR(45) NULL,
  `avaliacoes` INT NULL,
  `numaval` INT NULL,
  PRIMARY KEY (`idprofissionais`),
  INDEX `fk_profissionais_pessoas_idx` (`pessoas_idpessoas` ASC),
  CONSTRAINT `fk_profissionais_pessoas`
    FOREIGN KEY (`pessoas_idpessoas`)
    REFERENCES `reformando_banco`.`pessoas` (`idpessoas`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `reformando_banco`.`usuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `reformando_banco`.`usuarios` (
  `idusuarios` INT NOT NULL AUTO_INCREMENT,
  `login` VARCHAR(45) NOT NULL,
  `senha` VARCHAR(45) NOT NULL,
  `pessoas_idpessoas` INT NOT NULL,
  PRIMARY KEY (`idusuarios`),
  UNIQUE INDEX `login_UNIQUE` (`login` ASC),
  INDEX `fk_usuarios_pessoas1_idx` (`pessoas_idpessoas` ASC),
  CONSTRAINT `fk_usuarios_pessoas1`
    FOREIGN KEY (`pessoas_idpessoas`)
    REFERENCES `reformando_banco`.`pessoas` (`idpessoas`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `reformando_banco`.`obras`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `reformando_banco`.`obras` (
  `idobras` INT NOT NULL AUTO_INCREMENT,
  `nomeobra` VARCHAR(45) NOT NULL,
  `descricao` VARCHAR(45) NOT NULL,
  `localizacao` VARCHAR(45) NOT NULL,
  `tipoprofissional` VARCHAR(45) NULL,
  `usuarios_idusuarios` INT NOT NULL,
  PRIMARY KEY (`idobras`),
  INDEX `fk_obras_usuarios1_idx` (`usuarios_idusuarios` ASC),
  CONSTRAINT `fk_obras_usuarios1`
    FOREIGN KEY (`usuarios_idusuarios`)
    REFERENCES `reformando_banco`.`usuarios` (`idusuarios`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;



SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
